### PR TITLE
Application code in top-level

### PR DESCRIPTION
**Pull request by sbose78**
I think it makes more sense to keep the 'well known' code structure of a codebase as is. Hence, renaming it to `pkg`.

### CODE REVIEW

**Comment by bigkevmcd** [comment]
I suspect that the `web` directory shouldn't be in `src` and should be moved to the top-level  instead.

**Comment by sbose78** [comment]
Fixed it.

**Comment by bigkevmcd** [comment]
Nitpicky, but most Go folks would expect the cmd to be in the top-level too ;-)

**Comment by sbose78** [comment]
Right ;)

**Comment by bigkevmcd** [comment]
Let's get the conflict resolved and this merged.

**Pull request closed without merging**
